name: Download and Update Repository

on:
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Git LFS
      run: |
        git lfs install

    - name: Install dependencies
      run: pip install requests

    - name: Run download and update script
      run: python ./.github/download_and_update.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update repository with latest release from tibia-oce/otclient"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
